# Generated by Django 3.1.6 on 2021-03-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [

        migrations.RunSQL(
            ''' DROP TABLE  IF EXISTS ov.companies CASCADE;
                CREATE TABLE ov.companies (
                cin BIGINT PRIMARY KEY,
                name VARCHAR,
                br_section VARCHAR,
                address_line VARCHAR,
                last_update TIMESTAMP WITHOUT TIME ZONE,
                created_at TIMESTAMP WITHOUT TIME ZONE,
                updated_at TIMESTAMP WITHOUT TIME ZONE
                );
                
            with temp as (
                    SELECT cin,
            corporate_body_name                          AS name,
            br_section,
            address_line                                 AS addr_line,
            updated_at,
            current_timestamp                            AS cr_at,
            current_timestamp                            as upd_at,
            row_number() over (partition by cin order by updated_at desc) as rn
            from ov.or_podanie_issues
            )
            INSERT INTO ov.companies
            SELECT cin, name, br_section, addr_line, temp.updated_at, cr_at, upd_at FROM temp WHERE rn = 1 AND cin IS NOT NULL
            ON CONFLICT (cin) DO NOTHING;

            with temp as (
            SELECT cin,
            corporate_body_name                          AS name,
            br_section,
            concat(street, ', ', postal_code, ' ', city) as addr_line,
            updated_at,
            current_timestamp                            as cr_at,
            current_timestamp                            as upd_at,
            row_number() over (partition by cin order by updated_at desc) as rn
            from ov.likvidator_issues
            )
            INSERT INTO ov.companies
            SELECT cin, name, br_section, addr_line, temp.updated_at, cr_at, upd_at FROM temp WHERE rn = 1 AND cin IS NOT NULL
            ON CONFLICT (cin) DO NOTHING;

        
            with temp as (
            SELECT cin,
            corporate_body_name                          AS name,
            concat(street, ', ', postal_code, ' ', city) as addr_line,
            updated_at,
            current_timestamp                            as cr_at,
            current_timestamp                            as upd_at,
            row_number() over (partition by cin order by updated_at desc) as rn
            from ov.konkurz_vyrovnanie_issues
            )
            INSERT INTO ov.companies
            SELECT cin, name, '', addr_line, temp.updated_at, cr_at, upd_at FROM temp WHERE rn = 1 AND cin IS NOT NULL
            ON CONFLICT (cin) DO NOTHING;

        
            with temp as (
            SELECT cin,
            corporate_body_name                          AS name,
            br_section,
            concat(street, ', ', postal_code, ' ', city) as addr_line,
            updated_at,
            current_timestamp                            as cr_at,
            current_timestamp                            as upd_at,
            row_number() over (partition by cin order by updated_at desc) as rn
            from ov.znizenie_imania_issues
            )
            INSERT INTO ov.companies
            SELECT cin, name, br_section, addr_line, temp.updated_at, cr_at, upd_at FROM temp WHERE rn = 1 AND cin IS NOT NULL
            ON CONFLICT (cin) DO NOTHING;

        with temp as (
            SELECT cin,
            corporate_body_name                          AS name,
            concat(street, ', ', postal_code, ' ', city) as addr_line,
            updated_at,
            current_timestamp                            as cr_at,
            current_timestamp                            as upd_at,
            row_number() over (partition by cin order by updated_at desc) as rn
            from ov.konkurz_restrukturalizacia_actors
            )
            INSERT INTO ov.companies
            SELECT cin, name, '', addr_line, temp.updated_at, cr_at, upd_at FROM temp WHERE rn = 1 AND cin IS NOT NULL
            ON CONFLICT (cin) DO NOTHING;

        ALTER TABLE ov.or_podanie_issues
        ADD COLUMN IF NOT EXISTS company_id BIGINT,
        ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
        REFERENCES ov.companies (cin)
        ON DELETE NO ACTION;
        
        UPDATE ov.or_podanie_issues SET company_id = cin WHERE cin IS NOT NULL;
        
        ALTER TABLE ov.likvidator_issues
        ADD COLUMN IF NOT EXISTS company_id BIGINT,
        ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
        REFERENCES ov.companies (cin)
        ON DELETE NO ACTION;
        
        UPDATE ov.likvidator_issues SET company_id = cin WHERE cin IS NOT NULL;
        
        ALTER TABLE ov.konkurz_vyrovnanie_issues
        ADD COLUMN IF NOT EXISTS company_id BIGINT,
        ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
        REFERENCES ov.companies (cin)
        ON DELETE NO ACTION;

        UPDATE ov.konkurz_vyrovnanie_issues SET company_id = cin WHERE cin IS NOT NULL;

        ALTER TABLE ov.znizenie_imania_issues
        ADD COLUMN IF NOT EXISTS company_id BIGINT,
        ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
        REFERENCES ov.companies (cin)
        ON DELETE NO ACTION;
    
        UPDATE ov.znizenie_imania_issues SET company_id = cin WHERE cin IS NOT NULL;

        ALTER TABLE ov.konkurz_restrukturalizacia_actors
        ADD COLUMN IF NOT EXISTS company_id BIGINT,
        ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
        REFERENCES ov.companies (cin)
        ON DELETE NO ACTION ;
        
         UPDATE ov.konkurz_restrukturalizacia_actors SET company_id = cin WHERE cin IS NOT NULL;
    ''')
    ]
